
export enum MessageRole {
	User = 'user',
	AI = 'ai'
}

export enum FileType {
	Preview = 'preview',
	Actual = 'actual',
	Original = 'original'
}

export interface Attachment {
	url: string;
	type: FileType;
}

export interface Usage {
	promptTokens: number;
	candidatesTokens: number;
	thinkingTokens?: number;
	totalTokens: number;
}

export interface UsageRecord {
	usage: Usage;
	cost: number;
}

export interface Message {
	id: string;
	role: MessageRole;
	content: string;
	isPending: boolean;
	files?: Attachment[];
	timeline?: TimelineSegment[];
	usage?: Usage;
	cost?: number;
	version?: number;
	editRefId?: string;
	createdAt: number;
}

export interface Thread {
	id: string
	title: string
	videoPath: string
	preprocessing: {
		/**
		 * Path to the extracted audio file (MP3/WAV).
		 * Used for transcription and as input for the timeline generation.
		 */
		audioPath?: string

		/**
		 * Path to the downscaled video file (usually 480p).
		 * Optimized for faster processing and lower token usage during scene detection and description.
		 */
		lowResVideoPath?: string;

		/**
		 * Path to the final, usable transcript JSON.
		 * This is the version used by the timeline generator (could be raw or corrected).
		 */
		transcriptPath?: string;

		/**
		 * Path to the initial raw transcript JSON extracted directly from audio.
		 * May contain inaccuracies or missing punctuation.
		 */
		rawTranscriptPath?: string;

		/**
		 * Path to the refined transcript JSON.
		 * Has been processed by an LLM to fix grammar, timestamps, and formatting.
		 */
		correctedTranscriptPath?: string;

		/**
		 * Path to the JSON file containing detected scene boundaries.
		 * Generated by the SceneDetector (e.g., using `scenedetect` CLI).
		 * Contains start/end times for visual scenes.
		 */
		sceneTimesPath?: string;

		/**
		 * Path to the JSON file containing visual descriptions for scenes.
		 * Generated by extracting frames from scenes and passing them to a vision model.
		 * Used to enrich the transcript with visual context.
		 */
		sceneDescriptionsPath?: string;
	}
	tempDir: string
	messages: Message[]
	versionCounter?: number
	createdAt: number
	updatedAt: number
}

export interface TimelineSegment {
	index: number
	start: string
	end: string
	text: string
	duration: number
}

export interface IntentResult {
	type: 'text' | 'generate-timeline';
	content: string; // Brief description or the text answer
	duration?: number; // Duration in seconds
}

export interface ModelPricing {
	input: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
		text?: number        // Only for Flash
		audio?: number       // Only for Flash
	}
	output: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
	}
}

export type OperationType = 'raw-transcript' | 'corrected-transcript' | 'intent' | 'timeline-new' | 'timeline-edit'

export interface ModelSelection {
	[key: string]: string // operation -> model name
}

export interface ModelSettings {
	pricing: Record<string, ModelPricing>
	selection: ModelSelection
}