
export enum MessageRole {
	User = 'user',
	AI = 'ai'
}

export enum FileType {
	Preview = 'preview',
	Actual = 'actual',
	Original = 'original'
}

export type BackgroundTaskState = 'pending' | 'running' | 'completed' | 'error'

export interface VideoMetadata {
	duration: number
	width: number
	height: number
	size: number
	codec: string
	fps: number
	format: string
    hasAudio: boolean
}

export interface BackgroundTask {
	id: string
	name: string
	state: BackgroundTaskState
	status?: string
	progress?: number
	error?: string
}

export interface Attachment {
	url: string;
	type: FileType;
	upscale2k?: string; // High-res 2K path
	upscale4k?: string; // High-res 4K path
}

export interface Usage {
	promptTokens: number;
	candidatesTokens: number;
	thinkingTokens?: number;
	totalTokens: number;
}

export interface UsageRecord {
	usage: Usage;
	cost: number;
}

export interface Message {
	id: string;
	role: MessageRole;
	content: string;
	isPending: boolean;
	files?: Attachment[];
	attachedImages?: string[]; // New: base64/paths of attached images
	timeline?: EnrichedTimelineSegment[];
	usage?: Usage;
	cost?: number;
	version?: number;
	editRefId?: string;
	resultType?: 'video' | 'thumbnail' | 'summary' | 'image';
	createdAt: number;
}

export interface Thread {
	id: string
	title: string
	type?: 'video' | 'image' // New
	videoPath?: string // Now optional
	preprocessing: {
		/**
		 * Path to the extracted audio file (MP3/WAV).
		 * Used for transcription and as input for the timeline generation.
		 */
		audioPath?: string

		/**
		 * Path to the downscaled video file (usually 480p).
		 * Optimized for faster processing and lower token usage during scene detection and description.
		 */
		lowResVideoPath?: string;

		/**
		 * Path to the final, usable transcript JSON.
		 * This is the version used by the timeline generator (could be raw or corrected).
		 */
		transcriptPath?: string;

		/**
		 * Path to the initial raw transcript JSON extracted directly from audio.
		 * May contain inaccuracies or missing punctuation.
		 */
		rawTranscriptPath?: string;

		/**
		 * Path to the refined transcript JSON.
		 * Has been processed by an LLM to fix grammar, timestamps, and formatting.
		 */
		correctedTranscriptPath?: string;

		/**
		 * Path to the JSON file containing detected scene boundaries.
		 * Generated by the SceneDetector (e.g., using `scenedetect` CLI).
		 * Contains start/end times for visual scenes.
		 */
		sceneTimesPath?: string;

		/**
		 * Path to the JSON file containing visual descriptions for scenes.
		 * Generated by extracting frames from scenes and passing them to a vision model.
		 * Used to enrich the transcript with visual context.
		 */
		sceneDescriptionsPath?: string;

		/**
		 * Path to the unified enriched transcript JSON.
		 * Merges text transcript with visual scene descriptions.
		 * Used as a source of truth for both video and thumbnail pipelines.
		 */
		enrichedTranscriptPath?: string;

		/**
		 * Reference frames extracted from the video or provided by the user.
		 */
		'reference-frames'?: string[]; // New

		/**
		 * Source images for image-based threads.
		 */
		sourceImages?: string[]; // New

		/**
		 * Extracted text data from all images.
		 */
		imageTextPath?: string; // New
	}
	tempDir: string
	messages: Message[]
	backgroundTasks?: Record<string, BackgroundTask>
	nodePositions?: Record<string, { 
		x: number; 
		y: number; 
		width?: number; 
		height?: number; 
		title?: string; 
		isFrame?: boolean; 
		parentNode?: string 
	}>
	versionCounter?: number
	videoMetadata?: VideoMetadata
	missing?: boolean
	createdAt: number
	updatedAt: number
}

export interface TimelineSegment {
	index: number
	start: string
	end: string
	text: string
	duration: number
}

export interface EnrichedTimelineSegment extends TimelineSegment {
	visual: string
}


export interface IntentResult {
	type: 'text' | 'generate-timeline' | 'generate-thumbnail' | 'generate-image'; // Added generate-image
	content: string; // Brief description or the text answer
	duration?: number; // Duration in seconds
	selectedIndices?: number[]; // indices for images to use
}

export interface ModelPricing {
	input: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
		text?: number        // Only for Flash
		audio?: number       // Only for Flash
	}
	output: {
		standard: number
		longContext?: number // Only for Pro
		threshold?: number   // Only for Pro
		image?: number       // Only for Image Gen
	}
}

export type OperationType = 'raw-transcript' | 'corrected-transcript' | 'intent' | 'timeline-new' | 'timeline-edit' | 'thumbnail' | 'scene-description' | 'image-extraction' | 'image-intent' | 'image-generation' | 'image-upscale'

export type UpscaleFactor = 'x2' | 'x4'

export interface ModelSelection {
	[key: string]: string // operation -> model name
}

export interface ModelSettings {
	pricing: Record<string, ModelPricing>
	selection: ModelSelection
}